export function getSuggestions(input: string) {
  return {
    suggestions: [
      {
        name: 'New Look',
        mapbox_id:
          'dXJuOm1ieHJldDo2cEJoNE9DOThWTXVXWEJBNUx2TVVhZmlrd2lMbTlMMVliT19ucXAwYUxJdFZNcDNyZlY5anI0UVlBb3JOajVweUYzM2o4QlpKMTVxX0c5M29JZjI0WlJXa3FidFl5azN0elJqbXI2Ynl4enRQTzc5ZWZvTGNUeXh0bkFKaUl3Nk9NSXJ0blZlbW5xMEVFSzNIOFQ0TUJXbWNKMVZFVEd6NmRoaXJGOUFYU2FVYzV0cG5GdkpzWkFBbno3cjZGSnBKbXA1TF9yajlOendjLWczNERPWnBnUlJ4c2h3TDAzZU02RE5lampDQ0lXN3k4cS1palRtNEttYnU1a2IwbUNOQVRwZV9FOXE2V0VNT2dsa0JsUTlyWXpiajhrbmtjMFNxdUFFNnc2QjQ5MElkWmRfZmNfY0V6bEcyNG16eDUxWTlhYmJNbml6ak45eUF2d0hld1BfOU5EMkxrNHJKOFF4d3lqUjh0WFBUNHU5TkNFcnlnS3JrS2pDT0ZoRlNUdGhlQlRNOU9UX2VHUGFzbEl5T1AxRDUyU3RINUhCejB6T2d2c3p3by0zc20wWlJOaGlmU3hqX1MtYjd6U1J2a1pPdmlYNmtibVVxYTM1OWNlTVctR1BCUjlkQWVuOUlqVWZNNVA4dExoS1d4UHR3LXhDVUpYUmZQVWpiUERIc3NWOVc3Q3NTVXYzQ2VlZ1N2T2RsM2xUWlNvRUMwUG1qMVFQOEduRnI1SzFlQjIxRlMtZkowWkdEYkFWc3ZUQmlxQThnRjlGOEwtU2xXTWY4cmZkY3dtdzVWQldOYkMwMktDaUxManRZZzVrVkNlekJjVHh4SHM2d2Zaa0MxcGoxOGh2OEg4M3NIQ29FOHhNZ2V3WHRjZk5YSWFXTFZ2Zm42Z0E5YTNCNU9CYTFFb29QUjFrUEwzNlh6bUxKOWRjZGhvWC1BQlE2T1VNRFpFMFBOQUtFRHBRZlpRS3A0aUpIbzluM3FCajV6S2YtVlBWcHBiOGlRbUp3c0RhakJLeHUxNXBaTC1fWU9PLTZod3otSFEtamN2bkNDZUw1MUwwT191STZseHpIc3RhMXlUSlYtQVBHTF9uZndWQ0RxcHI5WUFQaHJRYUdxN3NqQlpoQjlabVRxem12Q3BGdlhadHpxaEhxUk9GVEp0OEhMTzc3ZDJZejcyYzJGektfZ08tSjkzSFBia3RWOXdSNURwSVhLTHNrdWZEZnhiRTdJTXVPcWlnV0lmXzhQSjZZRk5MOE1pdHVJckJzVTdfdHhfdmZ1QTFDQ0tXckttbUQ5UGxpRDVla0J4anZVX0lhOXJvalpGMmVBSFNoVXRucl8tdG1xUGxEbnB2c290N1JRX3NqVHlINndydXJPbzd3WmRzVG5tMUtBVVNaY0pJYnZHRk9YLXlxNW1mSnJfeThVak1qRGNaWHpQdE84QmlYdEd2aE1sVUoxcEUxQWtpbWhVVGNCV3QzdG9TaGdQZWtHT2xqV2pKWlE2dXBRZnlob2pydFZXZktMZHBBeWhwMVp1cDNobjMzd2NtOHZCcklEazZkWDNHZElZWHItTWRYampTa1EwRWNhbGlfdFpwTTRBTlJYOXF2THhTRmJnUVZTY2R0MnFILWtOc2dseGpiUFZ4NjRnekpLRktXVTFxd21CZmVGbDUzeFg4eGQ1UEl2REliQTJNeDJxeVNJcDBodGdGNEhFM00wUDcyQXRqNkRyOXMzdmh4VGpveGg3Qm9qM1pCRmNiRkEwQjF5bjRUMm91eU1KNlhmbXZqNTNQU2tSSndPdG5oUjU2VEFIWHYwX0N4TXV5aEJTbjJabE9fNGhMZlRGbENWZVJSZnlRNTYtRTltNXZrMWMtZWR2UHZPSjlDa05yUE56d3o3MzNIcG9XVVVXcnlKM0hYM0huNHNsOVdMUzk4VkFyYXozTVFnYm96eWFJUVRwREItRVViRGR3MXVlTjRvVG9WYXVzYUlaWVJaT3djek9TcV9YYXF3MklNYkdHd3RSUWRORDAxd3YyN2dvRGJHVlJEME9sdS00bUFhMmVHQTJ1SXZUZWpaNDBvVWZJNE9HWXRFQVdkcHZkaWlwTTJabnc3NWhCQXBJVWlKRXNhMlhfRklLUVdKd2JDTzN6bGRiN1lxZHhQSUNfTkJMakFBd1FmQ3RSTnVhelN1WjBmRXM1NmcyQVRlQzFZU0xnTS1JMTlBUjNHOE15WHhiUzd3eDdVd1BFemhJOHFlZFhCa2wzeGdnU0kyNjl0NFExbnBsQkFEeWZNdHlBUW1ISXdMc1Y4ZlRPYTFNdUVacXlLT1loUlViaEZGeFJ4NHBaYVlxZ3RlY0Q0RXhEXy1SYVlZM1QtTWdzNWlwc3h2c2h5WFFkQjk5Z19TRnR4RllBaFZhWmdtSFJUV05JTjRKNTBpMGZLMFpEMy10N1JuWE5QQ3RPNm96NmFPMG14NXgzTjFiNTBYcHlWMDRGNExEakx6SzlYSkVtV2s4U0owbGhYZDV3Yk9rR2hJWGFJTmg1Sk92aWZnSGRveU8zLW5Cd3JSWVFTRW8wcmhqZlRYQTlGWnhKempWemdZNGpWUGlobkZ2N0JaVXVHRXp5N21JVTVpUjVKOTJwRUNrb3hzNTBJVlFiUmRjZklJVThvUFJEOE12Rm1MZ0MwZDdHa3p5NVd0SndnbmFvVi1fZ3ROV3A5NzVsbWhlQ28tM0MzWHNEbkZaVl9jZ3d0azVraDlOazZkTnR1OGt0Nk9PRkNNbEZfOTQ2WTZwWDJ2UlBBY29yeC1uaGJia0VsdjB4TXIwNUxuWXM4X0xrLXJyU1lIa0JtWFZDLUR4MGJZd0t0VlVXOWE2R2dQSVJRdGFJNmlPclRjbFdFWTFZcTRxZUJzMGUxSHRmVXpZbERNb3dZS0xUSjMtR29Fc3o1S0VPNjRWbjNMNm9qYk5fOFhJWFc5NXlERDA3eEVxSzJVS2ZEWHFDcWtPUU9VQmlhTWNMTjN0Rkp4dXc=',
        feature_type: 'brand',
        place_formatted: 'Brand',
        context: {},
        language: 'en',
        brand: ['New Look'],
        external_ids: {},
      },
      {
        name: 'Stanford in New York Center',
        mapbox_id: 'dXJuOm1ieHBvaS1vc206bjQzMzg5NTgyMzE',
        feature_type: 'poi',
        address: '915 Broadway',
        full_address:
          '915 Broadway, 10010, New York, United States, America, United States of America, US, USA',
        place_formatted:
          '10010, New York, United States, America, United States of America, US, USA',
        context: {
          country: { name: 'US' },
          postcode: { name: '10010' },
          address: {
            name: '915 Broadway',
            address_number: '915',
            street_name: 'broadway',
          },
          street: { name: 'broadway' },
        },
        language: 'en',
        maki: 'marker',
        poi_category: ['Education', 'University, Universities'],
        poi_category_ids: ['education', 'university'],
        external_ids: { id_osm: 'n4338958231' },
        distance: 100,
      },
      {
        name: 'Lucky News',
        mapbox_id: 'dXJuOm1ieHBvaS1vc206bjI3MDQwODEwNzA',
        feature_type: 'poi',
        address: '248 East 23rd Street',
        full_address:
          '248 East 23rd Street, 10010, New York, NY, NYC, New York City, United States, America, United States of America, US, USA',
        place_formatted:
          '10010, New York, NY, NYC, New York City, United States, America, United States of America, US, USA',
        context: {
          country: { name: 'US' },
          postcode: { name: '10010' },
          address: {
            name: '248 East 23rd Street',
            address_number: '248',
            street_name: 'east 23rd street',
          },
          street: { name: 'east 23rd street' },
        },
        language: 'cs',
        maki: 'marker',
        poi_category: ['Samoobsluze, Mini market', 'Obchod s potravinami', 'Nakupování'],
        poi_category_ids: ['convenience_store', 'grocery', 'shopping'],
        external_ids: { id_osm: 'n2704081070' },
        distance: 800,
      },
      {
        name: 'Veteran Affairs New York Harbor Healthcare System',
        mapbox_id: 'dXJuOm1ieHBvaS1vc206dzE0Njk2NzAyOA',
        feature_type: 'poi',
        address: '423 East 23rd Street',
        full_address:
          '423 East 23rd Street, 10010, New York, United States, America, United States of America, US, USA',
        place_formatted:
          '10010, New York, United States, America, United States of America, US, USA',
        context: {
          country: { name: 'US' },
          postcode: { name: '10010' },
          address: {
            name: '423 East 23rd Street',
            address_number: '423',
            street_name: 'east 23rd street',
          },
          street: { name: 'east 23rd street' },
        },
        language: 'en',
        maki: 'marker',
        poi_category: [
          'Health Services',
          'Hospital, Hospitals, Hospital Center, Hospital Centers, Hospital Centre, Hospital Centres',
          'Services',
        ],
        poi_category_ids: ['health_services', 'hospital', 'services'],
        external_ids: { id_osm: 'w146967028' },
        distance: 1200,
      },
      {
        name: 'Newark Airport',
        name_preferred: 'Newark International Airport',
        mapbox_id: 'dXJuOm1ieHBvaTpjZjVkMWE3Zi05ZTQ1LTRiZjctODQ4OS1kMzBmODA4NDZkNGU',
        feature_type: 'poi',
        address: '3 Brewster Road',
        full_address: '3 Brewster Road, Newark, New Jersey 07114, United States',
        place_formatted: 'Newark, New Jersey 07114, United States',
        context: {
          country: {
            name: 'United States',
            country_code: 'US',
            country_code_alpha_3: 'USA',
          },
          region: {
            name: 'New Jersey',
            region_code: 'NJ',
            region_code_full: 'US-NJ',
          },
          postcode: { id: 'dXJuOm1ieHBsYzpBU211N0E', name: '07114' },
          place: { id: 'dXJuOm1ieHBsYzpEYVJvN0E', name: 'Newark' },
          address: {
            name: '3 Brewster Road',
            address_number: '3',
            street_name: 'brewster road',
          },
          street: { name: 'brewster road' },
        },
        language: 'en',
        maki: 'airport',
        poi_category: ['airport'],
        poi_category_ids: ['airport'],
        external_ids: { iata: 'EWR' },
        metadata: {},
        distance: 17000,
        operational_status: 'active',
      },
    ],
    attribution:
      '© 2024 Mapbox and its suppliers. All rights reserved. Use of this data is subject to the Mapbox Terms of Service. (https://www.mapbox.com/about/maps/)',
    response_id:
      'dvCsu_xXi66rMTotPSVuv-BpZZ9hSm0IUTDrnXFEl9dA61bL0OxUKDcDDZdNk1MAoDxcfBmLUz2Ouvf2netIZrpwPOJX7XgmASi7',
    url: 'https://api.mapbox.com/search/searchbox/v1/suggest?q=new&access_token=pk.eyJ1IjoiZXhhbXBsZXMiLCJhIjoiY2p0MG01MXRqMW45cjQzb2R6b2ptc3J4MSJ9.zA2W0IkI0c6KaAhJfk9bWg&language=en&session_token=0a5a0b88-d783-4d81-8922-3b209950dea8&proximity=-73.990593%2C40.740121',
  };
}

export const retrieveDetails = (id: string) => {
  return {
    type: 'FeatureCollection',
    features: [
      {
        type: 'Feature',
        geometry: {
          coordinates: [-73.98675894, 40.70276768],
          type: 'Point',
        },
        properties: {
          name: 'new look fresh start',
          mapbox_id: 'dXJuOm1ieHBvaTphNmEwNDVjNy03ZDcxLTQ1OTgtODExNi1iOTM0MWFlMjAzNjg',
          feature_type: 'poi',
          address: '68 Jay St',
          full_address: '68 Jay St, Brooklyn, New York 11201, United States',
          place_formatted: 'Brooklyn, New York 11201, United States',
          context: {
            country: {
              name: 'United States',
              country_code: 'US',
              country_code_alpha_3: 'USA',
            },
            region: {
              name: 'New York',
              region_code: 'NY',
              region_code_full: 'US-NY',
            },
            postcode: {
              id: 'dXJuOm1ieHBsYzpBYVdPN0E',
              name: '11201',
            },
            place: {
              id: 'dXJuOm1ieHBsYzpEZTVJN0E',
              name: 'New York City',
            },
            locality: {
              id: 'dXJuOm1ieHBsYzpBLzBLN0E',
              name: 'Brooklyn',
            },
            neighborhood: {
              id: 'dXJuOm1ieHBsYzpDbkVNN0E',
              name: 'Dumbo',
            },
            address: {
              name: '68 Jay St',
              address_number: '68',
              street_name: 'jay st',
            },
            street: {
              name: 'jay st',
            },
          },
          coordinates: {
            latitude: 40.70276768,
            longitude: -73.98675894,
            routable_points: [
              {
                name: 'default',
                latitude: 40.702762072697695,
                longitude: -73.98666792917028,
              },
            ],
          },
          language: 'en',
          maki: 'marker',
          poi_category: ['fashion accessories', 'shopping'],
          poi_category_ids: ['fashion_accessory_shop', 'shopping'],
          brand: ['New Look'],
          brand_id: ['new_look'],
          external_ids: {
            dataplor: '4fd964c8-b00b-4f7c-b007-a28ba8f96578',
          },
          metadata: {},
          _debug: {
            request: {
              raw_query: 'new',
              raw_encoded_query: 'new',
              normalized_query: 'new',
              parsed_query: {
                city: 'new',
              },
              tokens: ['new'],
              params: {
                access_token:
                  'pk.eyJ1IjoiZXhhbXBsZXMiLCJhIjoiY2p0MG01MXRqMW45cjQzb2R6b2ptc3J4MSJ9.zA2W0IkI0c6KaAhJfk9bWg',
                language: 'en',
                limit: null,
                proximity: '-73.990593,40.740121',
                origin: null,
                navigation_profile: null,
                time_deviation: null,
                sar_type: null,
                eta_type: null,
                country: null,
                types: null,
                poi_category: null,
                bbox: null,
                radius: null,
                user_proximity: '31.7863,41.4539',
                user_country: 'Turkey',
                session_token: '0a5a0b88-d783-4d81-8922-3b209950dea8',
                user_id: null,
                cps_time_period: null,
                cps_parking_type: null,
                cps_raw: null,
                debug: null,
                rich_metadata_provider: null,
                poi_category_exclusions: null,
                original_query: null,
                query_source: null,
                nav_device_id: null,
                nav_brand: null,
                nav_engine: null,
                nav_vehicle_classes: null,
                nav_production_year: null,
                nav_country_of_sale: null,
                nav_head_unit_generation: null,
                nav_offers_per_campaign_limit: null,
                nav_offer_active_at_least_until: null,
                nav_zoom_level: null,
                nav_ad_formats: null,
                show_closed_pois: true,
                language_source: 'request',
                auto_complete: null,
                nav_bearing: null,
                nav_layer: null,
                nav_exclude: null,
                nav_max_height: null,
                nav_max_width: null,
                nav_max_weight: null,
                nav_avoid_maneuver_radius: null,
                nav_include: null,
                viewport: null,
                viewport_ts: null,
              },
              uuid: '5a313036-589a-471b-947c-c251f3dd3210',
              feature_flags: {
                search_sbs_loqate_addresses: false,
                loqate_uk_data: false,
                cps_data: false,
                sbs_suggest_premium_data: false,
                plugshare_data: false,
                geocoder_permanent: true,
                sbs_allow_global: true,
                japan_poi: true,
                anwb_data: true,
                search_location_details: true,
                api_ads_exchange: false,
                search_poi_auto: false,
                yandex_data: false,
                osm_poi_data: true,
                closed_poi_data: true,
                google_poi_data: false,
                brand_search_data: false,
                search_endpoint: false,
                phone_search: false,
                japan_address_english: false,
              },
              edge_request_id: 'l12ZHSEGMVAj8BYTmyCBbspHVh7dk0kngJQyyp3bdgwcj_PVgx_z_w==',
              elb_trace_id:
                'Self=1-66f29c35-1db324ae412617b8771e8a53;Root=1-66f29c35-028c6a45044a1bfb01392d6d;x-edge-request-id=l12ZHSEGMVAj8BYTmyCBbspHVh7dk0kngJQyyp3bdgwcj_PVgx_z_w==',
              referer: 'https://docs.mapbox.com/',
              permanent: null,
              search_mode: 'suggest',
              query_signals: {
                tokens: ['new'],
                flags: {
                  skip_jp_address: false,
                },
                intent_tags: {
                  en: [
                    {
                      token: 'new',
                      detail: [],
                    },
                  ],
                },
                countries: {
                  user: ['TR'],
                  proximity: ['US'],
                  user_proximity: ['TR'],
                },
              },
              abtest_variants: {
                id: 'data-abtest-experiment',
                grp: 'control',
                ver: 'global_v1',
              },
              minimum_candidate_limit: 30,
              proximity_source: 'param',
              account_id:
                'eyJmbGFncyI6eyJhbndiX2RhdGEiOnRydWUsImNsb3NlZF9wb2lfZGF0YSI6dHJ1ZSwiZGlyZWN0aW9uc19ldl9jaGFyZ2VfYXRfdXNlcl9wcm92aWRlZF9jcyI6dHJ1ZSwiZW50ZXJwcmlzZV9ib3VuZGFyaWVzIjp0cnVlLCJldl9yb3V0aW5nIjp0cnVlLCJnZW9jb2Rlcl9wZXJtYW5lbnQiOnRydWUsImlzb2Nocm9uZV9kZXBhcnRfYXQiOnRydWUsImlzb2Nocm9uZV9tdWx0aXBvbHlnb24iOnRydWUsImphcGFuX3BvaSI6dHJ1ZSwibGl2ZV90aWxlc2V0cyI6dHJ1ZSwibXRzX3NxX2ttX3ByaWNpbmciOnRydWUsIm9zbV9wb2lfZGF0YSI6dHJ1ZSwic2JzX2FsbG93X2dsb2JhbCI6dHJ1ZSwic2VhcmNoX2xvY2F0aW9uX2RldGFpbHMiOnRydWUsInVzZV9wbXRpbGVzX2J1bmRsZSI6dHJ1ZSwid3JpdGVfcG10aWxlc19idW5kbGUiOnRydWV9LCJsaW1pdHMiOnsidGVycmFpblJhdGUiOjEwLCJtYXBzUmF0ZSI6MTAwMDAwLCJnZW9jb2RpbmdTZWFyY2hCb3hSYXRlIjo1MH0sImlkIjoiZXhhbXBsZXMiLCJkaXNhYmxlZCI6ZmFsc2V9',
              api_version: 'searchbox',
            },
            carmen_feature: null,
            yandex_poi_feature: null,
            yandex_address_feature: null,
            poi_feature: {
              type: 'Feature',
              geometry: {
                type: 'Point',
                coordinates: [-73.98675894, 40.70276768],
              },
              properties: {
                id: 'dXJuOm1ieHBvaTphNmEwNDVjNy03ZDcxLTQ1OTgtODExNi1iOTM0MWFlMjAzNjg',
                text: 'new look fresh start',
                category_ids: ['fashion_accessory_shop', 'shopping'],
                category: ['fashion accessories', 'shopping'],
                place_name:
                  'new look fresh start, 68 Jay St, Brooklyn, New York 11201, United States',
                external_ids: {
                  dataplor: '4fd964c8-b00b-4f7c-b007-a28ba8f96578',
                },
                internal_id: 'dXJuOm1ieHBvaTphNmEwNDVjNy03ZDcxLTQ1OTgtODExNi1iOTM0MWFlMjAzNjg',
                context: [
                  {
                    layer: 'address',
                    text: '68 Jay St',
                  },
                  {
                    layer: 'street',
                    text: 'jay st',
                  },
                  {
                    layer: 'postcode',
                    text: '11201',
                    id: 'dXJuOm1ieHBsYzpBYVdPN0E',
                  },
                  {
                    layer: 'country_code',
                    text: 'US',
                  },
                  {
                    layer: 'region_code',
                    text: 'US-NY',
                  },
                  {
                    layer: 'neighborhood',
                    text: 'Dumbo',
                    id: 'dXJuOm1ieHBsYzpDbkVNN0E',
                  },
                  {
                    layer: 'place',
                    text: 'New York City',
                    id: 'dXJuOm1ieHBsYzpEZTVJN0E',
                  },
                  {
                    layer: 'locality',
                    text: 'Brooklyn',
                    id: 'dXJuOm1ieHBsYzpBLzBLN0E',
                  },
                  {
                    layer: 'region',
                    text: 'New York',
                  },
                  {
                    layer: 'country',
                    text: 'United States',
                  },
                ],
                icon: 'marker',
                highlight: [],
                brand: ['New Look'],
                brand_id: ['new_look'],
                metadata: {
                  phone: '+17187831528',
                  website: 'http://newlookfreshstart.com/',
                  primary_photo_urls: [],
                  opening_hours:
                    'Mo 07:00-21:00; Tu 07:00-21:00; We 07:00-21:00; Th 07:00-21:00; Fr 07:00-21:00; Sa 08:00-20:00; Su 10:00-19:00',
                },
                _extendedSource: {
                  prominence: 1.0161804163238668,
                  score: 0,
                  normalizedProminence: 80,
                },
                extended_feature_name: [],
                routable_points: {
                  points: [
                    {
                      coordinates: [-73.98666792917028, 40.702762072697695],
                    },
                  ],
                },
                operational_status: null,
                closed_score: 1,
                reality_score: 0.7001999999999999,
              },
              data_source: 'brand',
            },
            loqate_find_item: null,
            google_features: null,
            applied_signals: null,
            similarity: null,
            spellcheck_debug: null,
            dedup_info: null,
          },
          operational_status: 'closed',
        },
      },
      {
        type: 'Feature',
        geometry: {
          coordinates: [-73.74196833, 40.67677305],
          type: 'Point',
        },
        properties: {
          name: 'New Look Inc',
          mapbox_id: 'dXJuOm1ieHBvaTpmZWExMjA5Yy03NWNlLTQ5YTEtYmU5Yi0wMzE3OGQ2MDNmYzk',
          feature_type: 'poi',
          address: '22805 Merrick Blvd',
          full_address: '22805 Merrick Blvd, Laurelton, New York 11413, United States',
          place_formatted: 'Laurelton, New York 11413, United States',
          context: {
            country: {
              name: 'United States',
              country_code: 'US',
              country_code_alpha_3: 'USA',
            },
            region: {
              name: 'New York',
              region_code: 'NY',
              region_code_full: 'US-NY',
            },
            postcode: {
              id: 'dXJuOm1ieHBsYzpBYSt1N0E',
              name: '11413',
            },
            place: {
              id: 'dXJuOm1ieHBsYzpEZTVJN0E',
              name: 'New York City',
            },
            locality: {
              id: 'dXJuOm1ieHBsYzpHeHRLN0E',
              name: 'Queens',
            },
            neighborhood: {
              id: 'dXJuOm1ieHBsYzpGU1RzN0E',
              name: 'Laurelton',
            },
            address: {
              name: '22805 Merrick Blvd',
              address_number: '22805',
              street_name: 'merrick blvd',
            },
            street: {
              name: 'merrick blvd',
            },
          },
          coordinates: {
            latitude: 40.67677305,
            longitude: -73.74196833,
            routable_points: [
              {
                name: 'default',
                latitude: 40.676698011227415,
                longitude: -73.74199448459294,
              },
            ],
          },
          language: 'en',
          maki: 'marker',
          poi_category: ['barber', 'services'],
          poi_category_ids: ['hairdresser', 'services'],
          brand: ['New Look'],
          brand_id: ['new_look'],
          external_ids: {
            dataplor: '4e43452f-ff3b-4e4c-aaa3-2ed327972ed8',
          },
          metadata: {},
          _debug: {
            request: {
              raw_query: 'new',
              raw_encoded_query: 'new',
              normalized_query: 'new',
              parsed_query: {
                city: 'new',
              },
              tokens: ['new'],
              params: {
                access_token:
                  'pk.eyJ1IjoiZXhhbXBsZXMiLCJhIjoiY2p0MG01MXRqMW45cjQzb2R6b2ptc3J4MSJ9.zA2W0IkI0c6KaAhJfk9bWg',
                language: 'en',
                limit: null,
                proximity: '-73.990593,40.740121',
                origin: null,
                navigation_profile: null,
                time_deviation: null,
                sar_type: null,
                eta_type: null,
                country: null,
                types: null,
                poi_category: null,
                bbox: null,
                radius: null,
                user_proximity: '31.7863,41.4539',
                user_country: 'Turkey',
                session_token: '0a5a0b88-d783-4d81-8922-3b209950dea8',
                user_id: null,
                cps_time_period: null,
                cps_parking_type: null,
                cps_raw: null,
                debug: null,
                rich_metadata_provider: null,
                poi_category_exclusions: null,
                original_query: null,
                query_source: null,
                nav_device_id: null,
                nav_brand: null,
                nav_engine: null,
                nav_vehicle_classes: null,
                nav_production_year: null,
                nav_country_of_sale: null,
                nav_head_unit_generation: null,
                nav_offers_per_campaign_limit: null,
                nav_offer_active_at_least_until: null,
                nav_zoom_level: null,
                nav_ad_formats: null,
                show_closed_pois: true,
                language_source: 'request',
                auto_complete: null,
                nav_bearing: null,
                nav_layer: null,
                nav_exclude: null,
                nav_max_height: null,
                nav_max_width: null,
                nav_max_weight: null,
                nav_avoid_maneuver_radius: null,
                nav_include: null,
                viewport: null,
                viewport_ts: null,
              },
              uuid: '5a313036-589a-471b-947c-c251f3dd3210',
              feature_flags: {
                search_sbs_loqate_addresses: false,
                loqate_uk_data: false,
                cps_data: false,
                sbs_suggest_premium_data: false,
                plugshare_data: false,
                geocoder_permanent: true,
                sbs_allow_global: true,
                japan_poi: true,
                anwb_data: true,
                search_location_details: true,
                api_ads_exchange: false,
                search_poi_auto: false,
                yandex_data: false,
                osm_poi_data: true,
                closed_poi_data: true,
                google_poi_data: false,
                brand_search_data: false,
                search_endpoint: false,
                phone_search: false,
                japan_address_english: false,
              },
              edge_request_id: 'l12ZHSEGMVAj8BYTmyCBbspHVh7dk0kngJQyyp3bdgwcj_PVgx_z_w==',
              elb_trace_id:
                'Self=1-66f29c35-1db324ae412617b8771e8a53;Root=1-66f29c35-028c6a45044a1bfb01392d6d;x-edge-request-id=l12ZHSEGMVAj8BYTmyCBbspHVh7dk0kngJQyyp3bdgwcj_PVgx_z_w==',
              referer: 'https://docs.mapbox.com/',
              permanent: null,
              search_mode: 'suggest',
              query_signals: {
                tokens: ['new'],
                flags: {
                  skip_jp_address: false,
                },
                intent_tags: {
                  en: [
                    {
                      token: 'new',
                      detail: [],
                    },
                  ],
                },
                countries: {
                  user: ['TR'],
                  proximity: ['US'],
                  user_proximity: ['TR'],
                },
              },
              abtest_variants: {
                id: 'data-abtest-experiment',
                grp: 'control',
                ver: 'global_v1',
              },
              minimum_candidate_limit: 30,
              proximity_source: 'param',
              account_id:
                'eyJmbGFncyI6eyJhbndiX2RhdGEiOnRydWUsImNsb3NlZF9wb2lfZGF0YSI6dHJ1ZSwiZGlyZWN0aW9uc19ldl9jaGFyZ2VfYXRfdXNlcl9wcm92aWRlZF9jcyI6dHJ1ZSwiZW50ZXJwcmlzZV9ib3VuZGFyaWVzIjp0cnVlLCJldl9yb3V0aW5nIjp0cnVlLCJnZW9jb2Rlcl9wZXJtYW5lbnQiOnRydWUsImlzb2Nocm9uZV9kZXBhcnRfYXQiOnRydWUsImlzb2Nocm9uZV9tdWx0aXBvbHlnb24iOnRydWUsImphcGFuX3BvaSI6dHJ1ZSwibGl2ZV90aWxlc2V0cyI6dHJ1ZSwibXRzX3NxX2ttX3ByaWNpbmciOnRydWUsIm9zbV9wb2lfZGF0YSI6dHJ1ZSwic2JzX2FsbG93X2dsb2JhbCI6dHJ1ZSwic2VhcmNoX2xvY2F0aW9uX2RldGFpbHMiOnRydWUsInVzZV9wbXRpbGVzX2J1bmRsZSI6dHJ1ZSwid3JpdGVfcG10aWxlc19idW5kbGUiOnRydWV9LCJsaW1pdHMiOnsidGVycmFpblJhdGUiOjEwLCJtYXBzUmF0ZSI6MTAwMDAwLCJnZW9jb2RpbmdTZWFyY2hCb3hSYXRlIjo1MH0sImlkIjoiZXhhbXBsZXMiLCJkaXNhYmxlZCI6ZmFsc2V9',
              api_version: 'searchbox',
            },
            carmen_feature: null,
            yandex_poi_feature: null,
            yandex_address_feature: null,
            poi_feature: {
              type: 'Feature',
              geometry: {
                type: 'Point',
                coordinates: [-73.74196833, 40.67677305],
              },
              properties: {
                id: 'dXJuOm1ieHBvaTpmZWExMjA5Yy03NWNlLTQ5YTEtYmU5Yi0wMzE3OGQ2MDNmYzk',
                text: 'New Look Inc',
                category_ids: ['hairdresser', 'services'],
                category: ['barber', 'services'],
                place_name:
                  'New Look Inc, 22805 Merrick Blvd, Laurelton, New York 11413, United States',
                external_ids: {
                  dataplor: '4e43452f-ff3b-4e4c-aaa3-2ed327972ed8',
                },
                internal_id: 'dXJuOm1ieHBvaTpmZWExMjA5Yy03NWNlLTQ5YTEtYmU5Yi0wMzE3OGQ2MDNmYzk',
                context: [
                  {
                    layer: 'address',
                    text: '22805 Merrick Blvd',
                  },
                  {
                    layer: 'street',
                    text: 'merrick blvd',
                  },
                  {
                    layer: 'postcode',
                    text: '11413',
                    id: 'dXJuOm1ieHBsYzpBYSt1N0E',
                  },
                  {
                    layer: 'country_code',
                    text: 'US',
                  },
                  {
                    layer: 'region_code',
                    text: 'US-NY',
                  },
                  {
                    layer: 'neighborhood',
                    text: 'Laurelton',
                    id: 'dXJuOm1ieHBsYzpGU1RzN0E',
                  },
                  {
                    layer: 'place',
                    text: 'New York City',
                    id: 'dXJuOm1ieHBsYzpEZTVJN0E',
                  },
                  {
                    layer: 'locality',
                    text: 'Queens',
                    id: 'dXJuOm1ieHBsYzpHeHRLN0E',
                  },
                  {
                    layer: 'region',
                    text: 'New York',
                  },
                  {
                    layer: 'country',
                    text: 'United States',
                  },
                ],
                icon: 'marker',
                highlight: [],
                brand: ['New Look'],
                brand_id: ['new_look'],
                metadata: {
                  phone: '+17185063150',
                  website: 'http://www.newlook.com/row',
                  primary_photo_urls: [],
                },
                _extendedSource: {
                  prominence: 0.2099900094990153,
                  score: 0,
                  normalizedProminence: 10,
                },
                extended_feature_name: [],
                routable_points: {
                  points: [
                    {
                      coordinates: [-73.74199448459294, 40.676698011227415],
                    },
                  ],
                },
                operational_status: null,
                closed_score: 0,
                reality_score: 0.7092961268921378,
              },
              data_source: 'brand',
            },
            loqate_find_item: null,
            google_features: null,
            applied_signals: null,
            similarity: null,
            spellcheck_debug: null,
            dedup_info: null,
          },
          operational_status: 'active',
        },
      },
      {
        type: 'Feature',
        geometry: {
          coordinates: [-79.97182165, 40.47943045],
          type: 'Point',
        },
        properties: {
          name: 'Anita New Look Wig Salon',
          mapbox_id: 'dXJuOm1ieHBvaTpmMjM2NWNkNC1mYWJjLTRjMmMtYWNjNC1lNjNjMjhkODViYmU',
          feature_type: 'poi',
          address: '226 Grant Ave',
          full_address: '226 Grant Ave, Millvale, Pennsylvania 15209, United States',
          place_formatted: 'Millvale, Pennsylvania 15209, United States',
          context: {
            country: {
              name: 'United States',
              country_code: 'US',
              country_code_alpha_3: 'USA',
            },
            region: {
              name: 'Pennsylvania',
              region_code: 'PA',
              region_code_full: 'US-PA',
            },
            postcode: {
              id: 'dXJuOm1ieHBsYzpBcEh1N0E',
              name: '15209',
            },
            place: {
              id: 'dXJuOm1ieHBsYzpETUNJN0E',
              name: 'Millvale',
            },
            address: {
              name: '226 Grant Ave',
              address_number: '226',
              street_name: 'grant ave',
            },
            street: {
              name: 'grant ave',
            },
          },
          coordinates: {
            latitude: 40.47943045,
            longitude: -79.97182165,
            routable_points: [
              {
                name: 'default',
                latitude: 40.479252,
                longitude: -79.97193,
              },
            ],
          },
          language: 'en',
          maki: 'marker',
          poi_category: ['shopping'],
          poi_category_ids: ['shopping'],
          brand: ['New Look'],
          brand_id: ['new_look'],
          external_ids: {
            dataplor: '220e0979-c730-45cc-994c-1eb8c7672a3b',
          },
          metadata: {},
          _debug: {
            request: {
              raw_query: 'new',
              raw_encoded_query: 'new',
              normalized_query: 'new',
              parsed_query: {
                city: 'new',
              },
              tokens: ['new'],
              params: {
                access_token:
                  'pk.eyJ1IjoiZXhhbXBsZXMiLCJhIjoiY2p0MG01MXRqMW45cjQzb2R6b2ptc3J4MSJ9.zA2W0IkI0c6KaAhJfk9bWg',
                language: 'en',
                limit: null,
                proximity: '-73.990593,40.740121',
                origin: null,
                navigation_profile: null,
                time_deviation: null,
                sar_type: null,
                eta_type: null,
                country: null,
                types: null,
                poi_category: null,
                bbox: null,
                radius: null,
                user_proximity: '31.7863,41.4539',
                user_country: 'Turkey',
                session_token: '0a5a0b88-d783-4d81-8922-3b209950dea8',
                user_id: null,
                cps_time_period: null,
                cps_parking_type: null,
                cps_raw: null,
                debug: null,
                rich_metadata_provider: null,
                poi_category_exclusions: null,
                original_query: null,
                query_source: null,
                nav_device_id: null,
                nav_brand: null,
                nav_engine: null,
                nav_vehicle_classes: null,
                nav_production_year: null,
                nav_country_of_sale: null,
                nav_head_unit_generation: null,
                nav_offers_per_campaign_limit: null,
                nav_offer_active_at_least_until: null,
                nav_zoom_level: null,
                nav_ad_formats: null,
                show_closed_pois: true,
                language_source: 'request',
                auto_complete: null,
                nav_bearing: null,
                nav_layer: null,
                nav_exclude: null,
                nav_max_height: null,
                nav_max_width: null,
                nav_max_weight: null,
                nav_avoid_maneuver_radius: null,
                nav_include: null,
                viewport: null,
                viewport_ts: null,
              },
              uuid: '5a313036-589a-471b-947c-c251f3dd3210',
              feature_flags: {
                search_sbs_loqate_addresses: false,
                loqate_uk_data: false,
                cps_data: false,
                sbs_suggest_premium_data: false,
                plugshare_data: false,
                geocoder_permanent: true,
                sbs_allow_global: true,
                japan_poi: true,
                anwb_data: true,
                search_location_details: true,
                api_ads_exchange: false,
                search_poi_auto: false,
                yandex_data: false,
                osm_poi_data: true,
                closed_poi_data: true,
                google_poi_data: false,
                brand_search_data: false,
                search_endpoint: false,
                phone_search: false,
                japan_address_english: false,
              },
              edge_request_id: 'l12ZHSEGMVAj8BYTmyCBbspHVh7dk0kngJQyyp3bdgwcj_PVgx_z_w==',
              elb_trace_id:
                'Self=1-66f29c35-1db324ae412617b8771e8a53;Root=1-66f29c35-028c6a45044a1bfb01392d6d;x-edge-request-id=l12ZHSEGMVAj8BYTmyCBbspHVh7dk0kngJQyyp3bdgwcj_PVgx_z_w==',
              referer: 'https://docs.mapbox.com/',
              permanent: null,
              search_mode: 'suggest',
              query_signals: {
                tokens: ['new'],
                flags: {
                  skip_jp_address: false,
                },
                intent_tags: {
                  en: [
                    {
                      token: 'new',
                      detail: [],
                    },
                  ],
                },
                countries: {
                  user: ['TR'],
                  proximity: ['US'],
                  user_proximity: ['TR'],
                },
              },
              abtest_variants: {
                id: 'data-abtest-experiment',
                grp: 'control',
                ver: 'global_v1',
              },
              minimum_candidate_limit: 30,
              proximity_source: 'param',
              account_id:
                'eyJmbGFncyI6eyJhbndiX2RhdGEiOnRydWUsImNsb3NlZF9wb2lfZGF0YSI6dHJ1ZSwiZGlyZWN0aW9uc19ldl9jaGFyZ2VfYXRfdXNlcl9wcm92aWRlZF9jcyI6dHJ1ZSwiZW50ZXJwcmlzZV9ib3VuZGFyaWVzIjp0cnVlLCJldl9yb3V0aW5nIjp0cnVlLCJnZW9jb2Rlcl9wZXJtYW5lbnQiOnRydWUsImlzb2Nocm9uZV9kZXBhcnRfYXQiOnRydWUsImlzb2Nocm9uZV9tdWx0aXBvbHlnb24iOnRydWUsImphcGFuX3BvaSI6dHJ1ZSwibGl2ZV90aWxlc2V0cyI6dHJ1ZSwibXRzX3NxX2ttX3ByaWNpbmciOnRydWUsIm9zbV9wb2lfZGF0YSI6dHJ1ZSwic2JzX2FsbG93X2dsb2JhbCI6dHJ1ZSwic2VhcmNoX2xvY2F0aW9uX2RldGFpbHMiOnRydWUsInVzZV9wbXRpbGVzX2J1bmRsZSI6dHJ1ZSwid3JpdGVfcG10aWxlc19idW5kbGUiOnRydWV9LCJsaW1pdHMiOnsidGVycmFpblJhdGUiOjEwLCJtYXBzUmF0ZSI6MTAwMDAwLCJnZW9jb2RpbmdTZWFyY2hCb3hSYXRlIjo1MH0sImlkIjoiZXhhbXBsZXMiLCJkaXNhYmxlZCI6ZmFsc2V9',
              api_version: 'searchbox',
            },
            carmen_feature: null,
            yandex_poi_feature: null,
            yandex_address_feature: null,
            poi_feature: {
              type: 'Feature',
              geometry: {
                type: 'Point',
                coordinates: [-79.97182165, 40.47943045],
              },
              properties: {
                id: 'dXJuOm1ieHBvaTpmMjM2NWNkNC1mYWJjLTRjMmMtYWNjNC1lNjNjMjhkODViYmU',
                text: 'Anita New Look Wig Salon',
                category_ids: ['shopping'],
                category: ['shopping'],
                place_name:
                  'Anita New Look Wig Salon, 226 Grant Ave, Millvale, Pennsylvania 15209, United States',
                external_ids: {
                  dataplor: '220e0979-c730-45cc-994c-1eb8c7672a3b',
                },
                internal_id: 'dXJuOm1ieHBvaTpmMjM2NWNkNC1mYWJjLTRjMmMtYWNjNC1lNjNjMjhkODViYmU',
                context: [
                  {
                    layer: 'address',
                    text: '226 Grant Ave',
                  },
                  {
                    layer: 'street',
                    text: 'grant ave',
                  },
                  {
                    layer: 'postcode',
                    text: '15209',
                    id: 'dXJuOm1ieHBsYzpBcEh1N0E',
                  },
                  {
                    layer: 'country_code',
                    text: 'US',
                  },
                  {
                    layer: 'region_code',
                    text: 'US-PA',
                  },
                  {
                    layer: 'place',
                    text: 'Millvale',
                    id: 'dXJuOm1ieHBsYzpETUNJN0E',
                  },
                  {
                    layer: 'region',
                    text: 'Pennsylvania',
                  },
                  {
                    layer: 'country',
                    text: 'United States',
                  },
                ],
                icon: 'marker',
                highlight: [],
                brand: ['New Look'],
                brand_id: ['new_look'],
                metadata: {
                  phone: '+18143975663',
                  primary_photo_urls: [],
                  opening_hours:
                    'Mo 10:00-16:30; Tu 10:00-17:30; We 10:00-16:30; Th 10:00-17:30; Fr 10:00-17:30; Sa 10:00-16:30',
                },
                _extendedSource: {
                  prominence: 4.409779976159334,
                  score: 0,
                  normalizedProminence: 100,
                },
                extended_feature_name: [],
                routable_points: {
                  points: [
                    {
                      coordinates: [-79.97193, 40.479252],
                    },
                  ],
                },
                operational_status: null,
                closed_score: 0,
                reality_score: 0.7685117647058823,
              },
              data_source: 'brand',
            },
            loqate_find_item: null,
            google_features: null,
            applied_signals: null,
            similarity: null,
            spellcheck_debug: null,
            dedup_info: null,
          },
          operational_status: 'active',
        },
      },
      {
        type: 'Feature',
        geometry: {
          coordinates: [-83.15889596, 40.14472378],
          type: 'Point',
        },
        properties: {
          name: 'New Look Fitness Apparel',
          mapbox_id: 'dXJuOm1ieHBvaTphNzVmY2VkNi1kOTgwLTRhMDEtYmNkYi0xMjg2NzQ4ZDM2NjQ',
          feature_type: 'poi',
          address: '8685 Finlarig Dr',
          full_address: '8685 Finlarig Dr, Dublin, Ohio 43017, United States',
          place_formatted: 'Dublin, Ohio 43017, United States',
          context: {
            country: {
              name: 'United States',
              country_code: 'US',
              country_code_alpha_3: 'USA',
            },
            region: {
              name: 'Ohio',
              region_code: 'OH',
              region_code_full: 'US-OH',
            },
            postcode: {
              id: 'dXJuOm1ieHBsYzpDSVhPN0E',
              name: '43017',
            },
            place: {
              id: 'dXJuOm1ieHBsYzpCV0hJN0E',
              name: 'Dublin',
            },
            neighborhood: {
              id: 'dXJuOm1ieHBsYzpHWElzN0E',
              name: 'Muirfield Village',
            },
            address: {
              name: '8685 Finlarig Dr',
              address_number: '8685',
              street_name: 'finlarig dr',
            },
            street: {
              name: 'finlarig dr',
            },
          },
          coordinates: {
            latitude: 40.14472378,
            longitude: -83.15889596,
            routable_points: [
              {
                name: 'default',
                latitude: 40.144831584619375,
                longitude: -83.15883111201056,
              },
            ],
          },
          language: 'en',
          maki: 'clothing-store',
          poi_category: ['clothes store', 'shopping'],
          poi_category_ids: ['clothing_store', 'shopping'],
          brand: ['New Look'],
          brand_id: ['new_look'],
          external_ids: {
            dataplor: 'd4054eba-1548-4325-9b96-e71acac4a222',
          },
          metadata: {},
          _debug: {
            request: {
              raw_query: 'new',
              raw_encoded_query: 'new',
              normalized_query: 'new',
              parsed_query: {
                city: 'new',
              },
              tokens: ['new'],
              params: {
                access_token:
                  'pk.eyJ1IjoiZXhhbXBsZXMiLCJhIjoiY2p0MG01MXRqMW45cjQzb2R6b2ptc3J4MSJ9.zA2W0IkI0c6KaAhJfk9bWg',
                language: 'en',
                limit: null,
                proximity: '-73.990593,40.740121',
                origin: null,
                navigation_profile: null,
                time_deviation: null,
                sar_type: null,
                eta_type: null,
                country: null,
                types: null,
                poi_category: null,
                bbox: null,
                radius: null,
                user_proximity: '31.7863,41.4539',
                user_country: 'Turkey',
                session_token: '0a5a0b88-d783-4d81-8922-3b209950dea8',
                user_id: null,
                cps_time_period: null,
                cps_parking_type: null,
                cps_raw: null,
                debug: null,
                rich_metadata_provider: null,
                poi_category_exclusions: null,
                original_query: null,
                query_source: null,
                nav_device_id: null,
                nav_brand: null,
                nav_engine: null,
                nav_vehicle_classes: null,
                nav_production_year: null,
                nav_country_of_sale: null,
                nav_head_unit_generation: null,
                nav_offers_per_campaign_limit: null,
                nav_offer_active_at_least_until: null,
                nav_zoom_level: null,
                nav_ad_formats: null,
                show_closed_pois: true,
                language_source: 'request',
                auto_complete: null,
                nav_bearing: null,
                nav_layer: null,
                nav_exclude: null,
                nav_max_height: null,
                nav_max_width: null,
                nav_max_weight: null,
                nav_avoid_maneuver_radius: null,
                nav_include: null,
                viewport: null,
                viewport_ts: null,
              },
              uuid: '5a313036-589a-471b-947c-c251f3dd3210',
              feature_flags: {
                search_sbs_loqate_addresses: false,
                loqate_uk_data: false,
                cps_data: false,
                sbs_suggest_premium_data: false,
                plugshare_data: false,
                geocoder_permanent: true,
                sbs_allow_global: true,
                japan_poi: true,
                anwb_data: true,
                search_location_details: true,
                api_ads_exchange: false,
                search_poi_auto: false,
                yandex_data: false,
                osm_poi_data: true,
                closed_poi_data: true,
                google_poi_data: false,
                brand_search_data: false,
                search_endpoint: false,
                phone_search: false,
                japan_address_english: false,
              },
              edge_request_id: 'l12ZHSEGMVAj8BYTmyCBbspHVh7dk0kngJQyyp3bdgwcj_PVgx_z_w==',
              elb_trace_id:
                'Self=1-66f29c35-1db324ae412617b8771e8a53;Root=1-66f29c35-028c6a45044a1bfb01392d6d;x-edge-request-id=l12ZHSEGMVAj8BYTmyCBbspHVh7dk0kngJQyyp3bdgwcj_PVgx_z_w==',
              referer: 'https://docs.mapbox.com/',
              permanent: null,
              search_mode: 'suggest',
              query_signals: {
                tokens: ['new'],
                flags: {
                  skip_jp_address: false,
                },
                intent_tags: {
                  en: [
                    {
                      token: 'new',
                      detail: [],
                    },
                  ],
                },
                countries: {
                  user: ['TR'],
                  proximity: ['US'],
                  user_proximity: ['TR'],
                },
              },
              abtest_variants: {
                id: 'data-abtest-experiment',
                grp: 'control',
                ver: 'global_v1',
              },
              minimum_candidate_limit: 30,
              proximity_source: 'param',
              account_id:
                'eyJmbGFncyI6eyJhbndiX2RhdGEiOnRydWUsImNsb3NlZF9wb2lfZGF0YSI6dHJ1ZSwiZGlyZWN0aW9uc19ldl9jaGFyZ2VfYXRfdXNlcl9wcm92aWRlZF9jcyI6dHJ1ZSwiZW50ZXJwcmlzZV9ib3VuZGFyaWVzIjp0cnVlLCJldl9yb3V0aW5nIjp0cnVlLCJnZW9jb2Rlcl9wZXJtYW5lbnQiOnRydWUsImlzb2Nocm9uZV9kZXBhcnRfYXQiOnRydWUsImlzb2Nocm9uZV9tdWx0aXBvbHlnb24iOnRydWUsImphcGFuX3BvaSI6dHJ1ZSwibGl2ZV90aWxlc2V0cyI6dHJ1ZSwibXRzX3NxX2ttX3ByaWNpbmciOnRydWUsIm9zbV9wb2lfZGF0YSI6dHJ1ZSwic2JzX2FsbG93X2dsb2JhbCI6dHJ1ZSwic2VhcmNoX2xvY2F0aW9uX2RldGFpbHMiOnRydWUsInVzZV9wbXRpbGVzX2J1bmRsZSI6dHJ1ZSwid3JpdGVfcG10aWxlc19idW5kbGUiOnRydWV9LCJsaW1pdHMiOnsidGVycmFpblJhdGUiOjEwLCJtYXBzUmF0ZSI6MTAwMDAwLCJnZW9jb2RpbmdTZWFyY2hCb3hSYXRlIjo1MH0sImlkIjoiZXhhbXBsZXMiLCJkaXNhYmxlZCI6ZmFsc2V9',
              api_version: 'searchbox',
            },
            carmen_feature: null,
            yandex_poi_feature: null,
            yandex_address_feature: null,
            poi_feature: {
              type: 'Feature',
              geometry: {
                type: 'Point',
                coordinates: [-83.15889596, 40.14472378],
              },
              properties: {
                id: 'dXJuOm1ieHBvaTphNzVmY2VkNi1kOTgwLTRhMDEtYmNkYi0xMjg2NzQ4ZDM2NjQ',
                text: 'New Look Fitness Apparel',
                category_ids: ['clothing_store', 'shopping'],
                category: ['clothes store', 'shopping'],
                place_name:
                  'New Look Fitness Apparel, 8685 Finlarig Dr, Dublin, Ohio 43017, United States',
                external_ids: {
                  dataplor: 'd4054eba-1548-4325-9b96-e71acac4a222',
                },
                internal_id: 'dXJuOm1ieHBvaTphNzVmY2VkNi1kOTgwLTRhMDEtYmNkYi0xMjg2NzQ4ZDM2NjQ',
                context: [
                  {
                    layer: 'address',
                    text: '8685 Finlarig Dr',
                  },
                  {
                    layer: 'street',
                    text: 'finlarig dr',
                  },
                  {
                    layer: 'postcode',
                    text: '43017',
                    id: 'dXJuOm1ieHBsYzpDSVhPN0E',
                  },
                  {
                    layer: 'country_code',
                    text: 'US',
                  },
                  {
                    layer: 'region_code',
                    text: 'US-OH',
                  },
                  {
                    layer: 'neighborhood',
                    text: 'Muirfield Village',
                    id: 'dXJuOm1ieHBsYzpHWElzN0E',
                  },
                  {
                    layer: 'place',
                    text: 'Dublin',
                    id: 'dXJuOm1ieHBsYzpCV0hJN0E',
                  },
                  {
                    layer: 'region',
                    text: 'Ohio',
                  },
                  {
                    layer: 'country',
                    text: 'United States',
                  },
                ],
                icon: 'clothing-store',
                highlight: [],
                brand: ['New Look'],
                brand_id: ['new_look'],
                metadata: {
                  phone: '+16143613351',
                  website: 'https://newlookfitnessapparel.com/',
                  primary_photo_urls: [],
                },
                _extendedSource: {
                  prominence: 0.9938122951113302,
                  score: 0,
                  normalizedProminence: 80,
                },
                extended_feature_name: [],
                routable_points: {
                  points: [
                    {
                      coordinates: [-83.15883111201056, 40.144831584619375],
                    },
                  ],
                },
                operational_status: null,
                closed_score: 0,
                reality_score: 0.7685117647058823,
              },
              data_source: 'brand',
            },
            loqate_find_item: null,
            google_features: null,
            applied_signals: null,
            similarity: null,
            spellcheck_debug: null,
            dedup_info: null,
          },
          operational_status: 'active',
        },
      },
      {
        type: 'Feature',
        geometry: {
          coordinates: [-85.99144838, 39.82755029],
          type: 'Point',
        },
        properties: {
          name: 'New Look Fashion',
          mapbox_id: 'dXJuOm1ieHBvaTpiOWExYjYzMC01MGQ3LTQ4ODAtYTIyMy0wOWQ1NTlhZmU0ZjU',
          feature_type: 'poi',
          address: '3816 N Mitthoefer Rd',
          full_address: '3816 N Mitthoefer Rd, Indianapolis, Indiana 46235, United States',
          place_formatted: 'Indianapolis, Indiana 46235, United States',
          context: {
            country: {
              name: 'United States',
              country_code: 'US',
              country_code_alpha_3: 'USA',
            },
            region: {
              name: 'Indiana',
              region_code: 'IN',
              region_code_full: 'US-IN',
            },
            postcode: {
              id: 'dXJuOm1ieHBsYzpDVVpPN0E',
              name: '46235',
            },
            place: {
              id: 'dXJuOm1ieHBsYzpDWGJJN0E',
              name: 'Indianapolis',
            },
            neighborhood: {
              id: 'dXJuOm1ieHBsYzpESWJzN0E',
              name: 'Far Eastside',
            },
            address: {
              name: '3816 N Mitthoefer Rd',
              address_number: '3816',
              street_name: 'n mitthoefer rd',
            },
            street: {
              name: 'n mitthoefer rd',
            },
          },
          coordinates: {
            latitude: 39.82755029,
            longitude: -85.99144838,
            routable_points: [
              {
                name: 'default',
                latitude: 39.82755158979021,
                longitude: -85.99136237721433,
              },
            ],
          },
          language: 'en',
          maki: 'clothing-store',
          poi_category: ['clothes store', 'shopping'],
          poi_category_ids: ['clothing_store', 'shopping'],
          brand: ['New Look'],
          brand_id: ['new_look'],
          external_ids: {
            dataplor: '81011dfc-0785-47ef-908a-f3f95d559581',
          },
          metadata: {},
          _debug: {
            request: {
              raw_query: 'new',
              raw_encoded_query: 'new',
              normalized_query: 'new',
              parsed_query: {
                city: 'new',
              },
              tokens: ['new'],
              params: {
                access_token:
                  'pk.eyJ1IjoiZXhhbXBsZXMiLCJhIjoiY2p0MG01MXRqMW45cjQzb2R6b2ptc3J4MSJ9.zA2W0IkI0c6KaAhJfk9bWg',
                language: 'en',
                limit: null,
                proximity: '-73.990593,40.740121',
                origin: null,
                navigation_profile: null,
                time_deviation: null,
                sar_type: null,
                eta_type: null,
                country: null,
                types: null,
                poi_category: null,
                bbox: null,
                radius: null,
                user_proximity: '31.7863,41.4539',
                user_country: 'Turkey',
                session_token: '0a5a0b88-d783-4d81-8922-3b209950dea8',
                user_id: null,
                cps_time_period: null,
                cps_parking_type: null,
                cps_raw: null,
                debug: null,
                rich_metadata_provider: null,
                poi_category_exclusions: null,
                original_query: null,
                query_source: null,
                nav_device_id: null,
                nav_brand: null,
                nav_engine: null,
                nav_vehicle_classes: null,
                nav_production_year: null,
                nav_country_of_sale: null,
                nav_head_unit_generation: null,
                nav_offers_per_campaign_limit: null,
                nav_offer_active_at_least_until: null,
                nav_zoom_level: null,
                nav_ad_formats: null,
                show_closed_pois: true,
                language_source: 'request',
                auto_complete: null,
                nav_bearing: null,
                nav_layer: null,
                nav_exclude: null,
                nav_max_height: null,
                nav_max_width: null,
                nav_max_weight: null,
                nav_avoid_maneuver_radius: null,
                nav_include: null,
                viewport: null,
                viewport_ts: null,
              },
              uuid: '5a313036-589a-471b-947c-c251f3dd3210',
              feature_flags: {
                search_sbs_loqate_addresses: false,
                loqate_uk_data: false,
                cps_data: false,
                sbs_suggest_premium_data: false,
                plugshare_data: false,
                geocoder_permanent: true,
                sbs_allow_global: true,
                japan_poi: true,
                anwb_data: true,
                search_location_details: true,
                api_ads_exchange: false,
                search_poi_auto: false,
                yandex_data: false,
                osm_poi_data: true,
                closed_poi_data: true,
                google_poi_data: false,
                brand_search_data: false,
                search_endpoint: false,
                phone_search: false,
                japan_address_english: false,
              },
              edge_request_id: 'l12ZHSEGMVAj8BYTmyCBbspHVh7dk0kngJQyyp3bdgwcj_PVgx_z_w==',
              elb_trace_id:
                'Self=1-66f29c35-1db324ae412617b8771e8a53;Root=1-66f29c35-028c6a45044a1bfb01392d6d;x-edge-request-id=l12ZHSEGMVAj8BYTmyCBbspHVh7dk0kngJQyyp3bdgwcj_PVgx_z_w==',
              referer: 'https://docs.mapbox.com/',
              permanent: null,
              search_mode: 'suggest',
              query_signals: {
                tokens: ['new'],
                flags: {
                  skip_jp_address: false,
                },
                intent_tags: {
                  en: [
                    {
                      token: 'new',
                      detail: [],
                    },
                  ],
                },
                countries: {
                  user: ['TR'],
                  proximity: ['US'],
                  user_proximity: ['TR'],
                },
              },
              abtest_variants: {
                id: 'data-abtest-experiment',
                grp: 'control',
                ver: 'global_v1',
              },
              minimum_candidate_limit: 30,
              proximity_source: 'param',
              account_id:
                'eyJmbGFncyI6eyJhbndiX2RhdGEiOnRydWUsImNsb3NlZF9wb2lfZGF0YSI6dHJ1ZSwiZGlyZWN0aW9uc19ldl9jaGFyZ2VfYXRfdXNlcl9wcm92aWRlZF9jcyI6dHJ1ZSwiZW50ZXJwcmlzZV9ib3VuZGFyaWVzIjp0cnVlLCJldl9yb3V0aW5nIjp0cnVlLCJnZW9jb2Rlcl9wZXJtYW5lbnQiOnRydWUsImlzb2Nocm9uZV9kZXBhcnRfYXQiOnRydWUsImlzb2Nocm9uZV9tdWx0aXBvbHlnb24iOnRydWUsImphcGFuX3BvaSI6dHJ1ZSwibGl2ZV90aWxlc2V0cyI6dHJ1ZSwibXRzX3NxX2ttX3ByaWNpbmciOnRydWUsIm9zbV9wb2lfZGF0YSI6dHJ1ZSwic2JzX2FsbG93X2dsb2JhbCI6dHJ1ZSwic2VhcmNoX2xvY2F0aW9uX2RldGFpbHMiOnRydWUsInVzZV9wbXRpbGVzX2J1bmRsZSI6dHJ1ZSwid3JpdGVfcG10aWxlc19idW5kbGUiOnRydWV9LCJsaW1pdHMiOnsidGVycmFpblJhdGUiOjEwLCJtYXBzUmF0ZSI6MTAwMDAwLCJnZW9jb2RpbmdTZWFyY2hCb3hSYXRlIjo1MH0sImlkIjoiZXhhbXBsZXMiLCJkaXNhYmxlZCI6ZmFsc2V9',
              api_version: 'searchbox',
            },
            carmen_feature: null,
            yandex_poi_feature: null,
            yandex_address_feature: null,
            poi_feature: {
              type: 'Feature',
              geometry: {
                type: 'Point',
                coordinates: [-85.99144838, 39.82755029],
              },
              properties: {
                id: 'dXJuOm1ieHBvaTpiOWExYjYzMC01MGQ3LTQ4ODAtYTIyMy0wOWQ1NTlhZmU0ZjU',
                text: 'New Look Fashion',
                category_ids: ['clothing_store', 'shopping'],
                category: ['clothes store', 'shopping'],
                place_name:
                  'New Look Fashion, 3816 N Mitthoefer Rd, Indianapolis, Indiana 46235, United States',
                external_ids: {
                  dataplor: '81011dfc-0785-47ef-908a-f3f95d559581',
                },
                internal_id: 'dXJuOm1ieHBvaTpiOWExYjYzMC01MGQ3LTQ4ODAtYTIyMy0wOWQ1NTlhZmU0ZjU',
                context: [
                  {
                    layer: 'address',
                    text: '3816 N Mitthoefer Rd',
                  },
                  {
                    layer: 'street',
                    text: 'n mitthoefer rd',
                  },
                  {
                    layer: 'postcode',
                    text: '46235',
                    id: 'dXJuOm1ieHBsYzpDVVpPN0E',
                  },
                  {
                    layer: 'country_code',
                    text: 'US',
                  },
                  {
                    layer: 'region_code',
                    text: 'US-IN',
                  },
                  {
                    layer: 'neighborhood',
                    text: 'Far Eastside',
                    id: 'dXJuOm1ieHBsYzpESWJzN0E',
                  },
                  {
                    layer: 'place',
                    text: 'Indianapolis',
                    id: 'dXJuOm1ieHBsYzpDWGJJN0E',
                  },
                  {
                    layer: 'region',
                    text: 'Indiana',
                  },
                  {
                    layer: 'country',
                    text: 'United States',
                  },
                ],
                icon: 'clothing-store',
                highlight: [],
                brand: ['New Look'],
                brand_id: ['new_look'],
                metadata: {
                  phone: '+13174438676',
                  website: 'http://www.newlook.com/row',
                  primary_photo_urls: [],
                  opening_hours:
                    'Mo 10:00-20:00; Tu 10:00-20:00; We 10:00-20:00; Th 10:00-20:00; Fr 10:00-21:00; Sa 10:00-21:00; Su 12:00-18:00',
                },
                _extendedSource: {
                  prominence: 98.00510190725328,
                  score: 0,
                  normalizedProminence: 100,
                },
                extended_feature_name: [],
                routable_points: {
                  points: [
                    {
                      coordinates: [-85.99136237721433, 39.82755158979021],
                    },
                  ],
                },
                operational_status: null,
                closed_score: 0,
                reality_score: 0.9004560480938482,
              },
              data_source: 'brand',
            },
            loqate_find_item: null,
            google_features: null,
            applied_signals: null,
            similarity: null,
            spellcheck_debug: null,
            dedup_info: null,
          },
          operational_status: 'active',
        },
      },
    ],
    attribution:
      '© 2024 Mapbox and its suppliers. All rights reserved. Use of this data is subject to the Mapbox Terms of Service. (https://www.mapbox.com/about/maps/)',
  };
};
